labels:
  issue: type:issue
  pull-request: type:pull-request
release:
  trigger:
    labels:
      - 'autorelease: pending'
  checklist: |
    ## ðŸš€ Release checklist

    ### Before release

     - [ ] Update the version in `manifest.json` to the same version as this PR
     - [ ] Update Google Store image before publish if the popup page's UI structure changed
